import { useState } from "react";
import type { Room } from "@/types/room";
import { priceValue } from "@/components/room-data";

export const BookingCard = ({ room }: { room: Room }) => {
  const [guestCount, setGuestCount] = useState(1);
  const nightlyPrice = priceValue(room.price);
  return <aside className="h-fit rounded-2xl border border-[#dddddd] p-6 shadow-[0_5px_18px_rgba(0,0,0,0.10)] lg:sticky lg:top-6" aria-label="Reservar alojamiento"><div className="flex items-baseline justify-between gap-3"><p><span className="text-xl font-bold">{room.price}</span> <span className="text-sm text-[#555555]">noche</span></p><span className="text-sm">★ {room.rating}</span></div><div className="mt-6 rounded-xl border border-[#b7b7b7]"><div className="border-b border-[#b7b7b7] p-3"><p className="text-[10px] font-bold uppercase">Huéspedes</p><div className="mt-2 flex items-center justify-between"><span className="text-sm">{guestCount} {guestCount === 1 ? "huésped" : "huéspedes"}</span><div className="flex items-center gap-2"><button className="flex h-8 w-8 items-center justify-center rounded-full border border-[#b7b7b7] text-lg disabled:cursor-not-allowed disabled:opacity-40" type="button" onClick={() => setGuestCount((count) => Math.max(1, count - 1))} disabled={guestCount === 1} aria-label="Reducir huéspedes">−</button><button className="flex h-8 w-8 items-center justify-center rounded-full border border-[#b7b7b7] text-lg disabled:cursor-not-allowed disabled:opacity-40" type="button" onClick={() => setGuestCount((count) => Math.min(room.guests, count + 1))} disabled={guestCount === room.guests} aria-label="Aumentar huéspedes">+</button></div></div></div><div className="grid grid-cols-2 divide-x divide-[#b7b7b7]"><div className="p-3"><p className="text-[10px] font-bold uppercase">Entrada</p><p className="mt-2 text-sm text-[#717171]">Agrega fecha</p></div><div className="p-3"><p className="text-[10px] font-bold uppercase">Salida</p><p className="mt-2 text-sm text-[#717171]">Agrega fecha</p></div></div></div><button className="mt-5 w-full rounded-xl bg-[#e31c5f] py-3.5 text-sm font-bold text-white transition-colors hover:bg-[#c91854]" type="button">Reservar</button><p className="mt-3 text-center text-xs text-[#717171]">Aún no se te cobrará nada</p><div className="mt-6 flex justify-between border-t border-[#eeeeee] pt-5 text-sm"><span>Precio por {guestCount} huésped{guestCount === 1 ? "" : "es"}</span><span>${nightlyPrice.toLocaleString("es-CO")} COP</span></div></aside>;
};
